### ISSUE TITLE
Existing Launch configuration not working with vscode 1.47.2

### ISSUE THREAD

**Issue by henri805** [microsoft/vscode-js-debug#645] opened 2020-07-20 23:17 UTC
**Describe the bug**
I used to start my debug sessions for my node/express app using this launch configuration
{
            "type": "node",
            "request": "launch",
            "name": "Debug GW:qa1",
            "preLaunchTask": "Build:Server",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "vscode:qa1"
            ],
            "port": 9229,
            "console": "integratedTerminal",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ]
        }
After upgrading to 1.47.2, the debugger stops and displays

```

> gateway@2.0.0 vscode:qa1 /Users/haltarac/workspace/alchemy/alc-gateway
> export NODE_ENV='qa1'; export TZ='GMT' ; node --inspect-brk dist/server.js

Debugger listening on ws://127.0.0.1:9229/86c69cd6-2937-4f41-ad25-8394acfad6a3
For help, see: https://nodejs.org/en/docs/inspector

```

I saw this in release notes:
You should not need to change any settings or launch configurations to take advantage of the new debugger. If you run into any problems, please open an issue!

**To Reproduce**

**Log File**

**VS Code Version:** 1.47.2
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/4950448/vscode-debugadapter-1.json.gz)

**Additional context**

**Comment by connor4312** [comment] 2020-07-20 23:43
I think this is an issue fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension), can you try that?

(This should also work if you just remove the --inspect-brk flag from the npm script.)

**Comment by docirl** [comment] 2020-07-21 14:41
hi @connor4312, I'm seeing a similar issue to above since updating to >=1.47 and only windows machines. we have a `launch.json` file for an application that worked before, but since the update it no longer starts.

Here what I see on the terminal on 1.47:
```
PS C:\Users\username\Documents\projects\project1>  cd 'c:\Users\username\Documents\projects\project1'; ${env:NODE_OPTIONS}='--require "c:/Users/username/.vscode/extensions/ms-vscode.js-debug-nightly-2020.7.2017/src/bootloader.bundle.js" '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.14320-5.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\username\\AppData\\Local\\Temp\\node-debug-callback-5fdb60ed21b149c0"}'; & 'C:\Program Files\nodejs\npm.cmd' 'run-script' 'start'
Debugger listening on ws://127.0.0.1:50198/ed8ad958-cb32-4af2-b712-73691e279782
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://1Debugger listening on ws://127.0.0.1:50202/dc688630-8a0a-4c63-947d-8d7a390945dc
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger lis
PS C:\Users\username\Documents\projects\project1>
```

On 1.46 I would get this:

```
PS C:\Users\username\Documents\projects\project1>  cd 'c:\Users\username\Documents\projects\project1'; & 'C:\Program Files\nodejs\npm.cmd' 'run-script' 'start'

> project1@0.0.1 start C:\Users\username\Documents\projects\project1
> ui5 serve --open test/flpSandbox.html#masterDetail-display --
```

My launch.json is this:
```
{
            "name": "Start project1",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "npm",
            "cwd": "c:\\Users\\username\\Documents\\projects\\project1",
            "windows": {
                "runtimeExecutable": "npm.cmd"
            },
            "runtimeArgs": [
                "run-script",
                "start"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "noDebug": true,
            "port": 9229,
            "env": {
                "DEBUG": "--inspect"
            }
        }
```

Trace output:
[vscode-debugadapter-5.json.gz](https://github.com/microsoft/vscode-js-debug/files/4954160/vscode-debugadapter-5.json.gz)

I have tried the latest vscode versions (todays `insiders` and the nightly build for `vscode-js-debug`) and this is still happening.

Any help you can provide here would be appreciated, thanks.

**Comment by connor4312** [comment] 2020-07-21 23:39
I think renaming `port` to `attachSimplePort`, and `type` to `pwa-node` _might_ fix this for you. Let me know if so.

**Comment by henri805** [comment] 2020-07-22 01:51
Hi Connor, AttachSimplePort and pwa-node are not available in the lauch.json 
![image](https://user-images.githubusercontent.com/57025423/88124979-29c2ad80-cb83-11ea-92ac-b7515951c666.png)

**Comment by henri805** [comment] 2020-07-22 02:33
If I set the "Debug > Node: Auto Attach" setting to "on" then it works. 
A bit clunky: it always stops in some internal helpers.js file but not too big a deal

**Comment by connor4312** [comment] 2020-07-22 03:57
> Hi Connor, AttachSimplePort and pwa-node are not available in the lauch.json

Sorry, I mean change `type: "node"` to `type: "pwa-node"` and `"port": 9229` to `"attachSimplePort": 9229`

**Comment by docirl** [comment] 2020-07-22 13:45
> I think renaming `port` to `attachSimplePort`, and `type` to `pwa-node` _might_ fix this for you. Let me know if so.

@connor4312 I tried this but it did not resolve the issue. In fact a new error was thrown trying this:

![image](https://user-images.githubusercontent.com/45471079/88183758-c63f8b00-cc29-11ea-87d2-bd40a36999a1.png)

Is there anything else  you can suggest? Or other logs that I can see to help debug this? Thanks

**Comment by connor4312** [comment] 2020-07-22 17:19
I did some research on the `ui5` and was able to repro locally using https://github.com/SAP/openui5-sample-app. To fix this, you can either:

- Remove the `"console": "integratedTerminal"` from your launch.json
- Use the next nightly build of the debugger, published when this comment is 7 hours old

Fixed with https://github.com/microsoft/vscode-js-debug/commit/c5a754ffdff5db6db413c00e3187cd09c8ed570e

**Closed by connor4312** 2020-07-22 17:19 UTC
Labels: bug

**Comment by roblourens** [comment] 2020-08-06 22:47
Can you tell me what you did to repro it with that repo? Looks like the issue is with debugging npm scripts and I can debug with the ones in the package.json fine.

**Comment by connor4312** [comment] 2020-08-06 22:53
The issue is specifically when running on an internal or external terminal on windows -- we track the target lifecycle to be the first process that connects back to the debugger. But the `npm.cmd` actually runs `npm-cli.js prefix -g` before running the 'real' npm process, so when that's done with think the session is over and kill any existing processes.
