### ISSUE TITLE
Running angular application in VS Code debugger causes chrome to crash 

### ISSUE THREAD

**Issue by singulli1** [microsoft/vscode-js-debug#729] opened 2020-08-29 12:23 UTC
**Describe the bug**

Currently developing angular applications in VSCode.  Working great for long time.
On 8/27 or 8/28 - 2 of the more complex applications starting crashing.

I have a simpler application that still worked fine.

The more complex ones would start loading ok, successfully process several pages of code to authenticate and login, then when redirecting to another module, everything would just close down.
Chrome would close, the application would stop running in the debugger.  No errors or messages.

The application would work just fine if I ran using just Chrome and the angular development server, taking VS code out of the loop.

In VS Code, I set "debug.javascript.usePreview" to false and everything started to work as normal again.

I'm attaching the log file you requested.
[vscode-debugadapter-14.json.gz](https://github.com/microsoft/vscode-js-debug/files/5145200/vscode-debugadapter-14.json.gz)

I'm also happy to help with any issues you might have to reproduce this error.
My company depends on VSCode and Angular and the great tools you are making.

**To Reproduce**

**Log File**

**VS Code Version:** Replace me!

**Additional context**

**Comment by connor4312** [comment] 2020-08-29 15:40
Is the crash listed on `chrome://crashes`? (note you'll need to open that in the debugged browser, since it uses a different user profile directory than your standard Chrome)

It looks like you're using the stable js-debug build, so nothing will have changed since 1.48 was released on the 7th. Maybe Chrome updated recently and introduced a bug...

**Comment by singulli1** [comment] 2020-08-29 16:15
No - nothing listed in chrome://crashes.  But when I rerun the debugger and it starts chrome again, I get a message stating chrome didn’t shut down properly, would you like to restore your session or something to that effect,

**Comment by mike-rivera** [comment] 2020-08-30 02:07
I have this same issue. It occurs when I have set in Visual Studio Code 
debug.javascript.usePreview": true

If I set it to false, it works fine.

There is a huge dump trace but here is what the top level states:

```
Process:               Google Chrome [20955]
Path:                  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Identifier:            com.google.Chrome
Version:               85.0.4183.83 (4183.83)
Code Type:             X86-64 (Native)
Parent Process:        Code Helper (Renderer) [19306]
Responsible:           Electron [2902]
User ID:               962186824

Date/Time:             2020-08-29 21:58:40.639 -0400
OS Version:            Mac OS X 10.14.6 (18G6020)
Report Version:        12
Anonymous UUID:        F41D0686-AA06-D163-BDF0-E4141ED72F1F


Time Awake Since Boot: 16000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
```

I have also tried using the nightly version of the extension but the errors get uglier.
This recently started happening (About 2 days ago)
I have attached the full dump file if it helps

[dump.txt](https://github.com/microsoft/vscode-js-debug/files/5146249/dump.txt)

**Comment by connor4312** [comment] 2020-08-30 02:25
I've opened a report on Chrome here: https://bugs.chromium.org/p/chromium/issues/detail?id=1123329 They published a new release on the 25th, which corresponds to these three crash reports.

Unfortunately it seems there's no (official) way to downgrade Chrome in the interim. You could try using Chrome Canary or dev versions (install and then set `runtimeExecutable: "canary"`) to see if the problem is fixed there,

**Comment by connor4312** [comment] 2020-08-31 15:22
@mike-rivera do you have a crash ID from `chrome://crashes` that I can share with the Chrome team? (You will need to open that in the debugged Chrome instance to see it)

**Comment by mike-rivera** [comment] 2020-08-31 15:26
Local Crash Context:	f40a8cac-8423-45e5-8b5b-213acb34cab9
Local Crash Context:	583aca71-a42f-4e11-a336-de90a4248f57
Local Crash Context:	da1cba1a-9a2a-4289-86db-fe7bbea063f8

**Comment by connor4312** [comment] 2020-08-31 16:01
Thanks!

**Comment by connor4312** [comment] 2020-08-31 17:27
@mike-rivera from the Chrome team:

>Thanks! Unfortunately, we can't do anything with the local context; we need something that looks like
> Uploaded Crash Report ID:	d002d34474278af2

**Comment by askerb** [comment] 2020-09-01 06:59
I'm seeing the same or similar issue in a React app I'm developing. Debugging with Chrome in VSCode causes Chrome to crash after authentication and during redirect. No problem running outside of debug session.
chrome://crashes shows crash each time. Uploaded the latest:

Uploaded crash report ID: | f78d657387e99a48

**Comment by askerb** [comment] 2020-09-01 07:11
Update: "debug.javascript.usePreview": false and the problem goes away for me.

**Comment by connor4312** [comment] 2020-09-01 15:10
Just guessing as to what might be causing Chrome to crash, if anyone can give this a shot:

1. Download [this custom build of the extension](https://memes.peet.io/img/js-debug-nightly-for-729.vsix)
1. Follow steps **1 and 2** for enabling the nightly extension here: https://github.com/microsoft/vscode-js-debug#nightly-extension
1. F1 and then "Install from VSIX", and choose the file you downloaded
1. Reload VS Code, and see if the problem still happens

**Comment by connor4312** [comment] 2020-09-01 15:18
It sounds like they have a fix merged into Chrome 86 already, so using the Canary build (https://github.com/microsoft/vscode-js-debug/issues/729#issuecomment-683367574) might work.

Closing this as it looks like it's confirmed to be a Chrome bug which will be resolved in the next release.

**Closed by connor4312** 2020-09-01 15:18 UTC
Labels: upstream

**Comment by connor4312** [comment] 2020-10-07 21:31
Chrome 86 where this should be fixed was released yesterday; update your browser and you should be good to go.
