### ISSUE TITLE
The debugger does not work in a monorepo when bundle size and sourcemaps go over a certain size

### ISSUE THREAD

**Issue by ShravanSunder** [microsoft/vscode-js-debug#1948] opened 2024-02-23 03:10 UTC
## **Describe the bug**
The debugger does not work in a monorepo when bundle size and sourcemaps go over a certain size.

The locals (variable view on hover) stops working.  And the line number of sourcemaps changes and is mismatched.

![2024-02-22 0202 Code honoApp ts — vscode-debug-reproduction](https://github.com/microsoft/vscode-js-debug/assets/5294949/39e90a43-9bcf-48f6-a81e-aab93c97dbea)

## **To Reproduce**
I've create a reproduction repo with a gutted version of my project

https://github.com/ShravanSunder/vscode-debug-reproduction
@connor4312 i've invited you to it the project, please let me know if you can see it

I've tried many launch configurations with sourcemap settings for attching to the worker debugging.  
In cloudflare's chrome debugger the line numbers and local variables values show up and are perfect.  It seems to only be an issue with vscode debugger.  

## **Log File**

here is the trace:

[vscode-debugadapter-04909eb4.json.gz](https://github.com/microsoft/vscode-js-debug/files/14381323/vscode-debugadapter-04909eb4.json.gz)

**VS Code Version:** 1.86.2

**Additional context**

**Comment by connor4312** [comment] 2024-02-23 16:43
Thanks for the good repro. This is likely because you're debugging minified code. Minified code will rename variables and have control flow changes so that lines and stepping may not work in the same way you expect them to with a 1:1 compilation. Your minifier also does not appear to making a rename entry for `coffeeRes`, so trying to access it fails.

For a better developer experience, I recommend configuring your tools to not minify your code in dev mode.

**Comment by ShravanSunder** [comment] 2024-02-23 17:43
@connor4312 I don't believe its due to magnification.  

The code is always minified.  
- However, when the bundle size is below a threshold it works fine i can see the runtime data in vscode.
- In the chrome debugger, with minification, i can always see the runtime data
- If the sourcemaps and other code exceed a certain size  (also minified) i don't see it.

**Comment by connor4312** [comment] 2024-02-23 17:55
What do you mean when you say "see runtime data"? Is the Variables view not populating?

**Comment by connor4312** [comment] 2024-02-23 18:25
The locals work for me without commenting things out -- could you share a trace log for a debug session where you get into the "stuck" state? It looks like the logs in the original issue were okay.

> i created this extra modules function. It has a bunch of large imports. If i enable it this is what i have for the locals and sourcemaps. The local variable names don't look scrambed, but they are not the same.


Can you push the code with that function to a branch in your repo?

**Comment by ShravanSunder** [comment] 2024-02-23 18:31
@connor4312 
 i just pushed the new commits

here is the trace with the module disabled
[vscode-debugadapter-f99a6c1c.json.gz](https://github.com/microsoft/vscode-js-debug/files/14388879/vscode-debugadapter-f99a6c1c.json.gz)


here is the trace with modules enabled
[vscode-debugadapter-fd379961.json.gz](https://github.com/microsoft/vscode-js-debug/files/14388882/vscode-debugadapter-fd379961.json.gz)

**Comment by connor4312** [comment] 2024-02-23 19:08
Thanks, I was able to reproduce the errors, seems like we had an off-by-one error which was pretty hard to see in unminified code, but in minified code where everything is one line it's more apparent.

I still didn't repro the case of the Variables view loading and never showing data -- do either of the log files you shared represent that?

**Comment by ShravanSunder** [comment] 2024-02-23 19:22
@connor4312 The loading spinner was just with `minify = false` in `wrangler.toml` .  i'll try to create a tracelog.  However, there is a issue
- if i put a breakpoint and it pauses while locals are spinning.  
- if i release the breakpoint and try to get it running nothing happens and locals are still spinning
- I think the debugger is frozen?  i'lve uploaded the trace log below

[vscode-debugadapter-d4cd0037.json.gz](https://github.com/microsoft/vscode-js-debug/files/14389282/vscode-debugadapter-d4cd0037.json.gz)


---
![2024-02-23 0222 Brave Browser The debugger does not work in a monorepo when bundle size and sourcemaps go over a certain size · Issue #1948 · microsoftvscode-js-debug](https://github.com/microsoft/vscode-js-debug/assets/5294949/0fb0e1f8-0c5e-4231-880f-547fbbb9a7cc)

**Comment by connor4312** [comment] 2024-02-23 19:52
Thanks, I can reproduce with that. This is actually the runtime freezing when we ask for the source of worker.js, which is needed in order to compute renames. I was able to reproduce the issue in Chrome and have opened an issue for the folks who work on V8: https://issues.chromium.org/issues/326554286

You can set `"sourceMapRenames": false,` in your configuration to disable the debugger's handling of renames, which would avoid the issue. Or continue to debug minified code.

I will close this issue again as I fixed the problem that was on our side in the linked PR.

**Closed by connor4312** 2024-02-23 19:52 UTC
Labels: bug, *out-of-scope

**Comment by ShravanSunder** [comment] 2024-02-23 20:56
thanks a lot for your help! @connor4312

**Comment by amunger** [comment] 2024-03-26 16:52
@connor4312 can you provide verification steps for the part that you fixed?

**Comment by connor4312** [comment] 2024-03-26 17:35
1. Open this zip [Archive.zip](https://github.com/microsoft/vscode-js-debug/files/14762403/Archive.zip)
2. Set a breakpoint somewhere in the quicksort function in index.js
3. In the JavaScript Debug Terminal, run `node min.js`
4. When the breakpoint is hit verify the names of variables in the **Variables** view are their original unminified versions

**Comment by segevfiner** [comment] 2025-01-07 13:33
@connor4312 It seems like the DAP implementation is running inside the extension host which has limited memory available: https://github.com/microsoft/vscode/issues/227692. I might help to move it to a separate process which can then have a custom memory limit which will greatly help here, as source maps are quite intensive on memory and I'm getting similar crashes on our repo. As since a change in how the extension host works, it is no longer possible to extend it's memory limit https://github.com/microsoft/vscode/issues/227692

**Comment by connor4312** [comment] 2025-01-07 16:37
Any chance you're able to get a heap snapshot of the process in that state? It'd be helpful to know what exactly is consuming your memory so I know what to move/optimize 🙂

**Comment by segevfiner** [comment] 2025-01-07 16:38
I wonder what's a good way to catch it before it crashes :P It is an OOM so it is hard to tell exactly when it will crash.

**Comment by connor4312** [comment] 2025-01-07 18:29
Yea, it's tricky. If you just get the log message from the crash (should be available in the Console when you Toggle Developer Tools) the backtrace might be a good hint.

**Comment by segevfiner** [comment] 2025-01-09 15:08
It got me this from the last crash:

[exthost-54cbb2.cpuprofile](https://github.com/user-attachments/files/18363324/exthost-54cbb2.cpuprofile)

<details><summary>Dev tools output</summary>
```
 INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:435  WARN UNRESPONSIVE extension host: 'ms-vscode.js-debug' took 100% of 5041.292ms, saved PROFILE here: 'file:///var/folders/2s/h5gc8qpj1x94_gm3jvs27pgw0000gn/T/exthost-54cbb2.cpuprofile'
api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22:1 
        
        
       Failed to load resource: the server responded with a status of 422 ()
log.ts:425  INFO Extension host (LocalProcess pid: 93813) is responsive.
localProcessExtensionHost.ts:275 Extension Host
localProcessExtensionHost.ts:276 <--- Last few GCs --->[93813:0x13c00270000]    74359 ms: Mark-Compact (reduce) 2733.7 (2763.1) -> 2730.9 (2747.9) MB, pooled: 0 MB, 509.00 / 0.00 ms  (average mu = 0.912, current mu = 0.942) last resort; GC in old space requested[93813:0x13c00270000]    74649 ms: Mark-Compact (reduce) 2730.9 (2747.9) -> 2730.9 (2747.6) MB, pooled: 0 MB, 290.17 / 0.00 ms  (average mu = 0.869, current mu = 0.000) last resort; GC in old space requested<--- JS stacktrace --->FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory----- Native stack trace ----- 1: 0x11ed320bc node::OnFatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 2: 0x1193460bc _$LT$font_types..tag..Tag$u20$as$u20$core..cmp..PartialEq$LT$$u5b$u8$u3b$$u20$4$u5d$$GT$$GT$::eq::h5661f81bf12469f3 [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 3: 0x119346050 _$LT$font_types..tag..Tag$u20$as$u20$core..cmp..PartialEq$LT$$u5b$u8$u3b$$u20$4$u5d$$GT$$GT$::eq::h5661f81bf12469f3 [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 4: 0x119511510 v8::CppHeap::CollectGarbageInYoungGenerationForTesting(cppgc::EmbedderStackState) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 5: 0x1194f05d4 v8::CppHeap::CollectGarbageInYoungGenerationForTesting(cppgc::EmbedderStackState) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 6: 0x1180f33d0 uv_tcp_simultaneous_accepts [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 7: 0x1194f1c7c v8::CppHeap::CollectGarbageInYoungGenerationForTesting(cppgc::EmbedderStackState) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 8: 0x119366d74 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 9: 0x11ee3c3e0 node::PromiseRejectCallback(v8::PromiseRejectMessage) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]10: 0x11ed0b488 node::Buffer::New(v8::Isolate*, char*, unsigned long) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]11: 0x177e0fef4 12: 0x170d2d0b8 13: 0x17013a2e0 14: 0x170e41e88 15: 0x177e0b028 16: 0x177e0ac74 17: 0x11946e444 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]18: 0x11946e0c4 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]19: 0x11935fc60 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]20: 0x11ec67c88 node::CallbackScope::~CallbackScope() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]21: 0x11ec734e4 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]22: 0x11ed3b298 node::OnFatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]23: 0x11ed3b810 node::OnFatalError(char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]24: 0x11ed2b6a8 node::Buffer::New(v8::Isolate*, char*, unsigned long) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]25: 0x1181316b0 uv_barrier_destroy [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]26: 0x118134d1c uv_async_send [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]27: 0x1181458b4 uv_free_interface_addresses [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]28: 0x1181351e4 uv_run [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]29: 0x1182ce804 node::FreeArrayBufferAllocator(node::ArrayBufferAllocator*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]30: 0x11b20f0e8 std::sys::pal::unix::os::errno::h028b0b83f8ef69bd [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]31: 0x11b22ee08 std::sys::pal::unix::os::errno::h028b0b83f8ef69bd [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]32: 0x11b1ced44 std::sys::pal::unix::os::errno::h028b0b83f8ef69bd [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]33: 0x11b22f6c8 std::sys::pal::unix::os::errno::h028b0b83f8ef69bd [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]34: 0x11b1f4b7c std::sys::pal::unix::os::errno::h028b0b83f8ef69bd [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]35: 0x11af4e66c v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]36: 0x1184824b8 v8::CodeEvent::GetScriptLine() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]37: 0x1184830fc v8::CodeEvent::GetScriptLine() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]38: 0x118481ad4 v8::CodeEvent::GetScriptLine() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]39: 0x118481d2c v8::CodeEvent::GetScriptLine() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]40: 0x118145f9c ElectronMain [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]41: 0x104fcca54  [/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)]42: 0x1865a3154 start [/usr/lib/dyld]
abstractExtensionService.ts:842 Extension host (LocalProcess pid: 93813) terminated unexpectedly. Code: 6, Signal: unknown
zb @ abstractExtensionService.ts:842
log.ts:445   ERR Extension host (LocalProcess pid: 93813) terminated unexpectedly. The following extensions were running: vscode.github-authentication, Vue.volar, vscode.emmet, vscode.npm, vscode.typescript-language-features, vscode.git-base, EditorConfig.EditorConfig, mhutchie.git-graph, ramyaraoa.show-offset, stkb.rewrap, yzhang.markdown-all-in-one, vitest.explorer, vscode.markdown-math, vscode.git, vscode.github, bierner.markdown-emoji, github.vscode-github-actions, matthewpi.caddyfile-support, hashicorp.hcl, ms-playwright.playwright, pulumi.pulumi-lsp-client, bierner.markdown-mermaid, Swimm.swimm, vscode.configuration-editing, vscode.extension-editing, vscode.json-language-features, jrieken.vscode-tree-sitter-query, vscode.debug-auto-launch, vscode.merge-conflict, dbaeumer.vscode-eslint, eamodio.gitlens, esbenp.prettier-vscode, GitHub.copilot, GitHub.copilot-chat, GitHub.vscode-pull-request-github, ms-vscode-remote.remote-containers, ms-vscode-remote.remote-wsl, stylelint.vscode-stylelint, vunguyentuan.vscode-css-variables, ms-vsliveshare.vsliveshare, firefox-devtools.vscode-firefox-debug, vscode.debug-server-ready, ms-vscode.js-debug, unifiedjs.vscode-mdx, VisualStudioExptTeam.intellicode-api-usage-examples, VisualStudioExptTeam.vscodeintellicode, vscode.markdown-language-features, humao.rest-client
```
</details>

If only I could run the extension host with `--heapsnapshot-near-heap-limit` (Assuming it still works in the Electron utility process stuff), and actually get a proper snapshot from it... But it doesn't look like I can do that without building VS Code myself ATM.
