### ISSUE TITLE
Instant crash when accessing navigator.getUserMedia

### ISSUE THREAD

**Issue by loadpixels** [microsoft/vscode-js-debug#400] opened 2020-03-18 10:30 UTC
Attempting to access the camera or microphone either through code or the console will result in the chrome instance crashing

- VS Code Version: 1.43.0
- Chrome Version 80
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Start a Chrome instance using VS Code Chrome Debug
2. Open console and paste in this line: navigator.getUserMedia({video:true},devices=>{console.log('hello')},err=>{console.log(err)})
3. Allow access to the camera
4. Chrome will crash without a trace

**Comment by roblourens** [comment] 2020-03-19 05:00
- old debug adapter: crash
- chrome devtools: works
- js-debug: I don't get the prompt from Chrome for camera access

**Comment by connor4312** [comment] 2020-03-19 15:06
This works for me in js-debug. Did you previously deny camera access on localhost:N? That would prevent it from prompting again.

![](https://memes.peet.io/img/20-03-310313bf-b5ee-4544-8971-2274201490c0.png)

**Comment by roblourens** [comment] 2020-03-19 15:35
Maybe, I changed the url to google.com and then I get the crash with js-debug too.

**Comment by connor4312** [comment] 2020-03-19 16:10
hm, still works for me there. Can you or loadpixels get a trace log?

**Comment by roblourens** [comment] 2020-03-19 18:43
The log shows a normal launch then disconnection, I don't think there's anything interesting. I tried with `"userDataDir": false`, setting a port to use that instead of the debug pipe, and commenting out all the flags we set when we spawn Chrome. 

One thing I noticed, if I start Chrome from the terminal and do this, then after I click Allow, I get a macOS prompt to allow iTerm access to the camera. So maybe vscode/Electron doesn't want to allow access to the camera.

**Comment by roblourens** [comment] 2020-03-19 18:56
@loadpixels what OS are you on?

**Comment by loadpixels** [comment] 2020-03-19 20:34
@roblourens  MacOS

echoing @connor4312 there's no tracelog to speak of, it just crashes

it happens as soon as I click the Allow button on the permissions dialog

**Comment by thovden** [comment] 2020-03-29 16:56
I experience the same problem. MacOS. I accept camera, and chrome immediately exits.

**Comment by roblourens** [comment] 2020-03-29 17:16
You can use an "attach" type config to work around this. I don't have anything better, sorry.

**Comment by connor4312** [comment] 2020-03-30 18:28
Doesn't seem to happen on Windows. Tracking upstream with: https://bugs.chromium.org/p/chromium/issues/detail?id=1066155

**Comment by connor4312** [comment] 2020-04-08 23:40
This will be fixed in https://github.com/microsoft/vscode/pull/94728

**Comment by connor4312** [comment] 2020-04-14 15:29
After discussion in the Chromium issue, we have opened a feature request here: https://bugs.chromium.org/p/chromium/issues/detail?id=1070364

Once that is ready we will need to do a small amount of work to support it.

**Comment by jacksonlauder** [comment] 2020-08-30 00:20
Hi, still no updates on this? My browser crashes for me too when trying to allow microphone permissions.

**Comment by amnporter** [comment] 2020-09-28 15:06
What's the workaround here?

**Comment by murray-minito** [comment] 2020-10-08 04:35
Work around:

Start Chrome with debug enabled 

OSX: 

# /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

use attach in launch.json

 "name": "Chrome",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "webRoot": "${workspaceFolder}/src",

**Comment by Odame** [comment] 2020-10-18 19:37
Perhaps helpful:

Starting chrome with debug enabled still crashes on MacOS once `navigator.mediaDevices.getUserMedia` is invoked.

**Google Chrome**  86.0.4240.80 (Official Build) (x86_64)
**OS** macOS Version 10.15.7
**Command Line**  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --remote-debugging-port=9222 --flag-switches-begin --flag-switches-end
**Debug Extension** v4.12.11

**Comment by robclouth** [comment] 2020-10-21 00:05
Has anyone found any reasonable workaround? It's difficult to debug applications that use MediaDevices.

**Comment by amnporter** [comment] 2020-10-21 00:15
@robclouth, use the suggestion from @murray-minito above. Not ideal, but works for now.

**Comment by Tereshka** [comment] 2020-11-20 04:47
**Chrome:** Version 87.0.4280.67 (Official Build) (x86_64)
**OS:** macOS Catalina 10.15.7
the problem is still here((

**Comment by robclouth** [comment] 2020-11-21 13:13
@amnporter it doesn't work. Still crashes when getUserMedia is called as @Odame has said, even when not debugging.

**Comment by amnporter** [comment] 2020-11-21 13:26
It's been working for me since trying it

**Comment by robclouth** [comment] 2020-11-21 13:31
On chrome 87.0.4280.67 if I start with ```--remote-debugging-port=9222``` and run ```navigator.getUserMedia({video:true},devices=>{console.log('hello')},err=>{console.log(err)})``` from the console it crashes, even without connecting vscode.

**Comment by robclouth** [comment] 2020-11-21 13:32
I think this is chrome issue, not vscode

**Comment by robclouth** [comment] 2020-11-21 13:33
```
[1121/143318.062403:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee480b000, 0x2000): (os/kern) invalid address (1)
[1121/143318.177972:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
```

**Comment by abhay-agarwal** [comment] 2020-11-21 18:00
This happens with the firefox VSCode debugger as well. It looks like running the debugging server on either FF or Chrome doesn't have the correct 'entitlements' on Mac OS, due to notarization changes with 10.14+. Any user media permissions will instantly crash the application. 

The only way out seems to be a separately notarized app dedicated to running as a debug server, with all these entitlements enabled.

**Comment by isometriq** [comment] 2021-01-05 23:01
I was able by allowing vscode permissions for camera and microphone, but I had to create these entitled permissions in first place.

Have a look at this:
https://github.com/microsoft/vscode/issues/95062#issuecomment-751241372

**Comment by Tereshka** [comment] 2021-01-08 10:54
@isometriq thank you, I tried the solution you provided, and it works! 

but I had to change the inserted code, because there were some other required fields in my access table:

```
INSERT into access (service, client, client_type, allowed, prompt_count) VALUES ("kTCCServiceCamera","com.microsoft.VSCode",0, 1, 0);
INSERT into access (service, client, client_type, allowed, prompt_count) VALUES ("kTCCServiceMicrophone","com.microsoft.VSCode",0, 1, 0);
```

**Comment by isometriq** [comment] 2021-01-10 21:08
@Tereshka hey you're right, I add to tweak some fields and value

**Comment by connor4312** [comment] 2021-04-29 23:13
This'll work in the next VS Code stable release.

**Closed** 2021-04-29 23:14 UTC
Labels: upstream
