### ISSUE TITLE
Source Maps not detected

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode-js-debug#489] opened 2020-05-27 14:12 UTC
Question 

I have source maps enabled in webpack, and chrome's debugger picks them up automatically : 
[image](https://i.imgur.com/ujKMheu.png).

When I look into the debug console I see bundle.js, so source maps are not working ?
[image](https://user-images.githubusercontent.com/23149166/83020751-3adeba80-a029-11ea-86d9-491a67e5c480.png)

If I ctrl + click  the white part it takes me to the correct part in the code. Breakpoints also work as expected.

Do I need to map sourceMapOverrides ?

Currently I have 
### launch.json
```json
    {
      "name": "Launch Chrome",
      "request": "launch",
      "type": "pwa-chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/client",
      "postDebugTask": "kill webpack"
    },
```
### webpack
```js
  entry: ['react-hot-loader/patch', path.resolve(__dirname, 'src')],
  output: {
    path: path.resolve(__dirname, 'public'),
    publicPath: '/public/js/',
    filename: 'bundle.js',
  }
```
### index.html
```html
<script src="http://localhost:8080/public/js/bundle.js"></script>
```

**Comment by connor4312** [comment] 2020-05-27 15:05
Give you're using console.error, this looks like a duplicate of https://github.com/microsoft/vscode-js-debug/issues/412. console.error doesn't "natively" map the paths of error objects passed to it; we just get a string with the stacktrace and will need to map its paths manually.

**Closed by connor4312** 2020-05-27 15:05 UTC
