### ISSUE TITLE
"debug.node.useV3" not recognised as an option on MacOS

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#290] opened 2020-02-03 17:44 UTC
On windows the option works fine, but on MacOS it doesn't seem to be recognised. Is this a known issue?

v2020.1.43263
![useV3](https://user-images.githubusercontent.com/936006/73676707-c0221600-46ac-11ea-948e-0f6f33283005.gif)

**Comment by connor4312** [comment] 2020-02-03 17:46
This is actually provided by the older debug extension, is your `ms-vscode.node-debug` extension outdated?

**Comment by jasonwilliams** [comment] 2020-02-03 17:49
I don't think ive ever had that plugin installed, was this baked into VSCode itself?

**Comment by connor4312** [comment] 2020-02-03 17:50
Yes, it's built-in. If you search for `ms-vscode.node-debug` in the extension view it should come up.

**Comment by jasonwilliams** [comment] 2020-02-03 17:50
oh i see it, its v1.41.1

**Comment by roblourens** [comment] 2020-02-03 17:51
Is this VS Code Insiders? It will only work in Insiders right now

**Comment by jasonwilliams** [comment] 2020-02-03 17:52
ah no, this is Stable

**Comment by connor4312** [comment] 2020-02-04 19:19
Thanks for the info. The useV3 option will be in stable in 1.42 which should be released later this week. Working as intended for the moment 🙂

**Closed by connor4312** 2020-02-04 19:19 UTC
Labels: needs more info
