### ISSUE TITLE
Exposes "vscode-remote" URIs when running in remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#286] opened 2020-01-30 22:50 UTC
- Connect to a remote
- Debug a node app and hit a breakpoint
- Breakpoints work but the script with the bp is replaced by a script from the DA with a `vscode-remote://` URI

![image](https://user-images.githubusercontent.com/323878/73497263-3ce08780-436f-11ea-900e-6177e8f62ee6.png)

DA seems to be returning the correct paths however

[debugadapter.txt](https://github.com/microsoft/vscode-js-debug/files/4136618/debugadapter.txt)

**Comment by roblourens** [comment] 2020-01-30 22:53
Oh could the difference vs the old DA be because it runs in the EH so the URI transformer runs? But the debug service should still be aware of this and display the correct paths @isidorn

**Comment by isidorn** [comment] 2020-01-31 10:13
fyi @weinand for uri transofrmation

**Comment by connor4312** [comment] 2020-02-05 23:17
Let me know if there's anything you need from me on this one. I've been using wsl/docker/vso more heavily recently and would love to use js-debug there 🙂

**Comment by weinand** [comment] 2020-02-06 09:53
I don't understand where this problem is showing up.
What exactly does the tiny screenshot in the first comment show?

What I did to reproduce this:
- connected VS Code to a remote linux box via SSH
- modified "type" in the launch.config to "pwa-node"
- F5

I hit the breakpoint and I do not see the file "test.js" showing up with two different paths:

![2020-02-06_10-30-19](https://user-images.githubusercontent.com/1898161/73924105-3ea8ce80-48cc-11ea-9d27-e23667860fa0.png)

---

How uri transformation works:
- VS Code debugger UI tunnels DAP over the extension host protocol because the DA always runs where the EH runs.
- The uri transformation automatically kicks in when URI objects are transferred via the extension host protocol (and when the EH runs remotely). 
- Since the DAP wire protocol represents URIs and file paths as strings, we have to convert all strings that are known to contain URIs or file paths into URI objects "in situ" before we tunnel the DAP request and we convert them back to strings in the EH after the tunnelling. This conversion makes them visible to the uri transformation. The knowledge of which strings are potentially URIs or paths is hardcoded here: https://github.com/microsoft/vscode/blob/9a839aa9f8102c8db4134fe768793c6f137bade9/src/vs/workbench/contrib/debug/common/debugUtils.ts#L172-L238. Whenever you add new string paths to the protocol (e.g. as custom private DAP events or requests), make sure to add them to the "convertPaths" function.

Other than that, there is no other URI conversion logic in the VS Code debugger UI.

**Comment by roblourens** [comment] 2020-02-06 22:10
I see this in one file but not other files. 

- Clone https://github.com/microsoft/vscode-smoketest-express/
- Set a breakpoint in `/bin/www` in `onListening`
- Start debugging, hit that breakpoint
- Hover `www` stackframe 
- There I see a `vscode-remote:` URL

But I don't see it on other files in that project like app.js or index.js. And actually, the DA is sending back a sourceReference for that www file. The DA shouldn't be sending a sourceReference for that file but also vscode shouldn't be showing a vscode-remote URI for it when it does.

**Comment by weinand** [comment] 2020-02-07 09:48
Could it be that the DA is sending back a source reference because the file is a bit unusual since it has no file extension?

**Comment by weinand** [comment] 2020-02-10 15:25
I did a comparison of running an express example in a remote (SSH) setup with our three debuggers: node, node2, and pwa-node.

Here are my findings (related to the vscode-remote URI issue):
- pwa-node: returns Source objects that have both a valid path and a sourceReference. This seems to surface the vscode-remote URI problem. In addition the "www" file from the express is read-only although the project has a r/w "www" file. 
- node2: returns Source objects that have either a valid path (exists on disk) or a sourceReference. There seems to be no vscode-remote URI problem. But similarly to pwa-node, the "www" file from the express sample is read-only although the project has a r/w "www" file.
- node (legacy): no vscode-remote URI problem and "www" file is writable.

**Comment by roblourens** [comment] 2020-02-10 22:40
I am not seeing node2 give a readonly file. But I see why it's happening with pwa-node and filed a new issue for it. It still seems wrong that it shows up with `vscode-remote` in that case though but we'll fix the sourceReference on our side.

**Comment by weinand** [comment] 2020-02-11 15:12
@roblourens @connor4312 please do not change anything for now since I'm still investigating the "TBD" part from my analysis.

**Comment by weinand** [comment] 2020-02-13 14:15
js-debug is actually returning "Source" objects with "sourceReference" > 0 (I thought that other debuggers would do this too, but that does not seem to be the case).

The problem with "sourceReference" > 0 is that it does not seem to work. VS Code always uses the "path". The DAP spec says that a "sourceReference" > 0 takes precedence over the path.

I've created an [issue](https://github.com/microsoft/vscode/issues/90593) for this.

**Comment by weinand** [comment] 2020-02-13 16:46
After my and Isi's fix for https://github.com/microsoft/vscode/issues/90593 "vscode-remote" URIs are no longer showing when running in remote.

**Closed by weinand** 2020-02-13 16:46 UTC
Labels: feature-request
