### ISSUE TITLE
Can't  attach to Edge when startup boost is enabled

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode-js-debug#1189] opened 2022-01-28 20:37 UTC
VS Code Version: 1.63.2
Edge version: Version 97.0.1072.76

Should it be possible  to attach to a running instance of Edge? I can't connect to a running instance of Edge, but I can connect to a running instance of Chrome. 

Both browsers are started with the flag --remote-debugging-port=9222 and only one browser instance was active at a time.

The Chrome attach configuration immediately attaches. If I try the Edge attach configuration, the run and debug loader just keeps loading and nothing seems to happen. These are the configurations:

![image](https://user-images.githubusercontent.com/69010225/151616115-1b042e36-6ebf-4544-92cf-f87145bdf097.png)

**Comment by connor4312** [comment] 2022-01-28 20:39
Can you collect a log file using the instructions in the issue template?

**Comment by billie-spektor** [comment] 2022-01-28 21:25
Sure, this log was created when running the Edge debug configuration. 
I did notice there  is some logging in there about Chrome extensions that I only have installed in Chrome and don't use in Edge. 

I think that the disconnect event at timestamp 1643403224405 was manually triggered by me from VSCode, after a few minutes of loading.

[vscode-debugadapter-6129bf3d_cleanedup.log](https://github.com/microsoft/vscode-js-debug/files/7961891/vscode-debugadapter-6129bf3d_cleanedup.log)

**Comment by billie-spektor** [comment] 2022-01-28 23:56
I think I've found the issue: an Edge process was starting in the background on Windows startup. I believe it may be related to a startup boost setting in the Edge settings:

![image](https://user-images.githubusercontent.com/69010225/151636896-5fd71215-885c-4d8e-84f7-22030a732c89.png)

This setting was automatically turned on. After killing the processes that were automatically started on Windows startup, the attach configuration immediately started working. 

I disabled the startup boost feature and attaching the debugger to a running instance of Edge works like a charm now. The startup boost setting disappeared from the Edge settings, so I can't toggle this setting to check if the problem returns (I did successfully apply the solution on two different machines though, so it definitely seems to be related to the startup processes). 

There has also been an Edge update today, so maybe that's related as well.

**Comment by connor4312** [comment] 2022-01-31 18:35
Thanks for digging in. I reached out to see if I can get more info on this from the Edge team.

**Comment by connor4312** [comment] 2022-03-03 23:06
According to https://support.microsoft.com/en-us/topic/get-help-with-startup-boost-ebef73ed-5c72-462f-8726-512782c5e442, it's actually a known thing that Startup Boost breaks debugging in Visual Studio (and it would be in VS Code too, since this debugger is used in both places!) Please try out the Canary channel, and let me know if it remains an issue. If so I will work to bubble this internally.

**Comment by Jims55jr** [comment] 2022-03-04 02:15
Helloworld!

**Comment by billie-spektor** [comment] 2022-03-04 13:35
Thanks for this information @connor4312. I just tried Edge Canary (Version 100.0.1181.0 (Official build) canary (64-bit)). The problem is also present there: I can't attach when startup boost is enabled, but I can attach when I turn off startup boost. I'll just keep startup boost turned off for now.

**Comment by connor4312** [comment] 2022-03-04 17:00
Thanks, I raised this issue internally. It was intended to be fixed on Chrome 89.

**Comment by toddreifsteck** [comment] 2022-03-04 17:50
I'm the developer of startup boost in Microsoft Edge. The issue that we fixed in Edge 89 was when a browser process was not already running.

The same issue with being unable to attach to an active browser will occur when any Chromium browser has a running browser process already active that does not have an open debugging port. In Chrome, this is common if a background extension is installed or when a PWA is running.

We will discuss and share more after we have agreed on a plan.

**Comment by toddreifsteck** [comment] 2022-03-04 18:34
@billie-spektor Could you confirm whether you are following these instructions to launch Edge prior to debugging?
https://code.visualstudio.com/docs/nodejs/browser-debugging#_attaching-to-browsers

If not, could you confirm how you are launching Edge prior to attempting to debug it?

**Comment by billie-spektor** [comment] 2022-03-04 21:26
Thanks for looking into this. I did not start Edge with the --user-data-dir argument, but only with the --remote-debugging-port. Previously, this seemed to be enough to be able to attach to Edge and I prefer to use my regular profile (that's the reason for me to use an attach configuration, instead of a launch configuration).

I just tested the following 3 scenario's, all with Canary:

1. 
Steps:
- run msedge.exe --remote-debugging-port=9222 --user-data-dir=remote-debug-profile
- try to attach the debugger

Results: 
- Edge opens
- Attaching the debugger works
- When I search for startup boost in the Edge settings, the option doesn't appear. So I can't validate whether startup boost is turned on or off

2. 
Steps:
- run msedge.exe --remote-debugging-port=9222
- try to attach the debugger

Results:
- Edge opens
- Attaching the debugger does not work
- When I search for startup boost in the Edge settings it does appear. It's toggled on

3. 

Steps:
- run msedge.exe --remote-debugging-port=9222
- search for the startup boost setting
- toggle it off
- close Edge
- run msedge.exe --remote-debugging-port=9222

Results:
- Edge opens
- Attaching the debugger works
- the startup boost setting can't be found anymore

I'm unsure why the startup boost setting disappears after toggling it off (and I believe I've also seen it disappear on my regular profile and reappear after restarting my computer). 

Scenario 3 seems to suggest that attaching the debugger works fine if launching Edge without the --user-data-dir argument, but only if startup boost is turned off.

**Comment by toddreifsteck** [comment] 2022-03-04 21:36
The startup boost setting is disabled and cannot be enabled for browsers with a remote debugging port enabled. It appears you have found a bug where this makes the setting disappear rather than being shown as disabled and greyed out as a remote-debugging-port disabled startup boost for that session. I'll put making a fix for that in my backlog.

There is another method to work-around startup boost being enabled. This is suboptimal and we can do better.

Steps:
- Know that I plan to debug so launch msedge.exe and then manually close it via the ... menu using Close Microsoft Edge
- run msedge.exe --remote-debugging-port=9222

Results:
- Edge opens
- Attaching debugger works
- The startup boost setting can't be found anymore (This is a bug. It should be visible, disabled and greyed out so a user cannot toggle it to enabled while a debugging port is open.)

**Comment by billie-spektor** [comment] 2022-03-20 20:21
Ah, that explains why the startup boost option wasn't always available. Thanks for the information and the work-around!

**Comment by toddreifsteck** [comment] 2022-03-20 21:54
When an Edge process is started with the remote debugging port and is not the singleton, we intend to have it exit and report an error to the console with instructions on how to close the copy of Edge blocking the debugging port from being created rather than opening a browser and having the debugging fail later. I'll share here after that fix is in Edge Canary.

**Comment by connor4312** [comment] 2022-12-15 22:07
Closing for housekeeping, as this is upstream on the Edge side to fix.

**Closed by connor4312** 2022-12-15 22:07 UTC
Labels: bug, upstream
