### ISSUE TITLE
step over / step into `eval` call fails when pauseForSourceMap is true

### ISSUE THREAD

**Issue by shashankvidiyalaC3** [microsoft/vscode-js-debug#1556] opened 2023-02-09 00:07 UTC
**Describe the bug**
When `pauseForSourceMap` is true and eval is called on a string that contains sourceMappingURL the step over/ step into fails and the debugger hits the next break point (like continue)
**To Reproduce**

1. compile any js file with babel using source maps flag
2. In another JS file make an eval call by using the contents of the compiled file as a string.
3. Create a launch configuration in VSCode with pauseForSourceMap as true
4. Add a break point  before the eval call 
5. Try to step over or step into this step would fail

**Log File**

[vscode-debugadapter-1af15ec5.json.gz](https://github.com/microsoft/vscode-js-debug/files/10691077/vscode-debugadapter-1af15ec5.json.gz)

**VS Code Version:**  
Version: 1.74.3

**Additional context**

https://user-images.githubusercontent.com/105740053/217680244-95b6ae47-7d0e-4988-9297-7153812d9d8a.mov

**Comment by connor4312** [comment] 2023-02-09 11:06
The `sourceURL` you provide is not a fully qualified URL (or an absolute file path, which we also accept since naughty tooling sometimes generates those). Thus, we don't know "where" the script is and cannot load sources in its sourcemap, and stepping into it is skipped via [smart stepping](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_smart-stepping).

Providing a fully qualified URI or absolute path in the sourceURL comment will resolve the issue.

**Comment by shashankvidiyalaC3** [comment] 2023-02-09 19:16
Hi Connor, thanks for the quick reply. Whether the source map is valid or invalid, I expect if I step over the eval code I should pause on line 9. Currently with pauseForSourceMap and also runtimeSourcemapPausePatterns config, it executes the rest of the program and pauses at the next breakpoint. (This happens regardless of the smartStep option).

**Comment by connor4312** [comment] 2023-03-03 21:10
Will be fixed in the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Closed** 2023-03-03 21:58 UTC
Labels: bug

**Comment by shashankvidiyalaC3** [comment] 2023-04-13 18:55
Hi, I am seeing the issue again It was working for me a week ago I was using 1.77.0 now this issue happens again to me when I use both nightly and 1.77.1.

**Comment by connor4312** [comment] 2023-04-13 21:22
I'm not able to reproduce that. Please collect a new log using the instructions in the issue template.
