### ISSUE TITLE
Breakpoints in typescript is not working

### ISSUE THREAD

**Issue by kristian1969** [microsoft/vscode-js-debug#1154] opened 2021-12-15 10:09 UTC
**Describe the bug**
I am setting a breakpoint in metricsRecorder.ts line 330 BUT when running code the line is automatically changed to 224!

Ran "Debug: Diagnose Breakpoint Problems" and got the following report out:

**Diagnose Breakpoint Problems Report**

✅ This breakpoint was initially set in:

/work/git/daas-azure/shared/metrics/metricsRecorder.ts line 330 column 1

✅ In the runtime, the breakpoint was set in:

file:///work/git/daas-azure/shared/metrics/metricsRecorder.js line 301 column 5 via this regex

file:///work/git/daas-azure/shared/metrics/metricsRecorder.ts line 330 column 1 via this regex

❓ We sent the breakpoint, but it didn't bind to any locations. If this is unexpected:
Make sure that your program is loading or running this script. You can add a debugger; statement to check this: your program will pause when it hits it.
If your breakpoint is set in certain places, such as on the last empty line of a file, the runtime might not be able to find anywhere to place it.
Unless you run with --nolazy, Node.js might not resolve breakpoints for code it hasn't parsed yet.
If necessary, make sure your compiled files are up-to-date with your source files.

✅ This breakpoint was initially set in:

/work/git/daas-azure/shared/metrics/metricsRecorder.ts line 342 column 1

✅ In the runtime, the breakpoint was set in:

file:///work/git/daas-azure/shared/metrics/metricsRecorder.js line 313 column 5 via this regex

file:///work/git/daas-azure/shared/metrics/metricsRecorder.ts line 342 column 1 via this regex

✅ The runtime acknowledged and adjusted the breakpoint, and it mapped back to the following locations:

/work/git/daas-azure/shared/metrics/metricsRecorder.ts line 224 column 1
If this is not right, your compiled code might be out of date with your sources. If you don't think this is the case and something else is wrong, please open an issue!

**VS Code Version:** 1.63.0

**Additional context**
Running Ubuntu

**Comment by connor4312** [comment] 2021-12-15 15:36
Please collect a trace log using the instructions in the issue template.

**Comment by mike-lischke** [comment] 2021-12-21 10:33
I hope it is ok to share this bug report for other people with the same issue. I have a pretty simple node application with a main.ts file and another which contains a class used in main.ts file. Breakpoints in main.ts resolve properly, but those in the other file do not. I can stop using the `debugger` command and set new breakpoints, which are then also hit. Existing breaks don't work however.

I checked the trace log file in the pwa analyzer and saw there's no source map resolve step. Maybe that's the cause of the trouble? The Diagnose Breakpoint Problems Report looks pretty much like the one mentioned by OP (with different files of course). All the suggested fixes were checked and found ok. So I'm now at the end of my ideas, how to get this working. @connor4312 I'll send my trace report in a minute to your mail address connor@xbox.com.

**Comment by connor4312** [comment] 2021-12-29 22:27
@mike-lischke it looks like the file was open / breakpoint was set in VS Code in `JavaToTypescriptConverter.ts`, but the path of the source file on disk is `JavaToTypeScriptConverter.ts` (notice the casing difference). I'm not sure how you managed to get into this spot, but unsetting the breakpoint in the file, closing all editors, and restarting VS Code should allow you to open a file in the correct casing in order to set the breakpoint.

**Comment by connor4312** [comment] 2021-12-29 22:27
Closing this issue as it's been two weeks without additional info from the reporter.

**Closed by connor4312** 2021-12-29 22:27 UTC
Labels: bug, needs more info

**Comment by mike-lischke** [comment] 2021-12-30 12:12
Sorry @connor4312, I totally missed your posting from 2 weeks ago. Thanks for answering to my question!

In fact I was able to solve the issue by, guess what, renaming the file, a few days ago (a restart and/or removing and adding back BPs did not help). Of course this is totally my fault, but it would be really helpful if the Breakpoint Problems Diagnose tool would include a check for file names.

**Comment by connor4312** [comment] 2021-12-30 15:58
Good idea, added that 🙂
