### ISSUE TITLE
Run without debugging doesn't work

### ISSUE THREAD

**Issue by valentin73** [microsoft/vscode-js-debug#628] opened 2020-07-16 04:42 UTC
After the new 1.47.1 update the option for 'run without debugging' isnt working anymore. Instead it says the debugger has been attached and it is waiting to get disconnected. But if i press start debugging it works like it should when i press 'run without debugging', BUT there are some red texts and the console output in between. I am extremely dissatisfied from this new update.

![212311](https://user-images.githubusercontent.com/56527596/87627641-d215e380-c737-11ea-9451-6592d08ed356.PNG)
![Capture](https://user-images.githubusercontent.com/56527596/87627643-d2ae7a00-c737-11ea-8077-d1951a1424ac.PNG)

**Comment by connor4312** [comment] 2020-07-16 04:49
The "debugger" messages will be hidden with https://github.com/microsoft/vscode-js-debug/issues/558. Subscribe to that issue for updates! I discussed why the debugger is still attached here: https://github.com/microsoft/vscode/issues/102057#issuecomment-656440073

The "process exited with code 0" is actually hidden already in the [latest nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) (so we'll only show that if the process exits with a non-zero 'error' code.)

Marking this as a duplicate of the first issue. Thanks for the report!

**Closed** 2020-07-16 04:49 UTC
Labels: *duplicate
