### ISSUE TITLE
Terminal inside Visual Studio Code starts debugger 

### ISSUE THREAD

**Issue by gbukauskas** [microsoft/vscode-js-debug#553] opened 2020-07-02 16:44 UTC
Terminal inside VS Code began reporting strange errors after last update: it looks that any command launches debugger before start.
(look at command 'npm run clean'). 
The command clean is "clean": "rimraf dist" and does not ask for debugger.
The same command launched from Windows Command Promt (outside Visual Studio Code) works well.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS G:\training\Angular\University\nestjs-course> cd .\rest-api\
PS G:\training\Angular\University\nestjs-course\rest-api> npm run clean
Debugger listening on ws://127.0.0.1:56599/a44429f5-7f03-44eb-8544-31acc365e04c
For help, see: https://nodejs.org/en/docs/inspector
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86060
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86087
    at Object.<anonymous> (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86383)
    at n (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:110)
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:902
    at Object.<anonymous> (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:56606/60cfad3e-fbf5-4f69-8f62-659c718d12cd
For help, see: https://nodejs.org/en/docs/inspector
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86060
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86087
    at Object.<anonymous> (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86383)
    at n (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:110)
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:902
    at Object.<anonymous> (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
Debugger attached.

> nestjs-course-backend@1.0.0 clean G:\training\Angular\University\nestjs-course\rest-api
> rimraf dist

Debugger listening on ws://127.0.0.1:56612/4154267b-e120-4341-943e-1078d4b42a64
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
    at Object.inspectorOpen [as open] (inspector.js:137:11)
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86060
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86087
    at Object.<anonymous> (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:86383)
    at n (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:110)
    at c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:902
    at Object.<anonymous> (c:\Users\gedas\AppData\Roaming\Code\User\workspaceStorage\7d65bb2692f87a047514e0eef68c8157\ms-vscode.js-debug\bootloader.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
PS G:\training\Angular\University\nestjs-course\rest-api>

**Comment by connor4312** [comment] 2020-07-02 16:57
This is [auto attach](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature). The error is a duplicate of https://github.com/microsoft/vscode-js-debug/issues/552

**Closed by connor4312** 2020-07-02 16:57 UTC
