### ISSUE TITLE
debug.javascript.autoAttachFilter: "always" does not work

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#733] opened 2020-09-01 09:41 UTC
Refs: https://github.com/microsoft/vscode/issues/105771

Have the following settings in your settings.json
```
"debug.node.autoAttach": "on",
"debug.javascript.usePreviewAutoAttach": true,
"debug.javascript.autoAttachFilter": "always"
```

1. Open our Smoke test express app
2. Open the integreted terminal
3. `node bin/www` does not get auto attached :bug:

If I do `node --inspect bin/www` it auto attaches nicely. 
This is not expected since I explicitly set `"debug.javascript.autoAttachFilter": "always"`

**Comment by connor4312** [comment] 2020-09-01 15:12
Note that if you changed the setting outside the workspace, you have to toggle auto attach to disabled then enabled for it to take effect (I need to fix this.) Does this sound like what you hit?

**Comment by connor4312** [comment] 2020-09-01 16:50
Closing as a tentative dupe of https://github.com/microsoft/vscode-js-debug/issues/731. Please let me know if you see this on the next Insiders.

**Closed** 2020-09-01 16:57 UTC
Labels: bug

**Comment by isidorn** [comment] 2020-09-01 18:29
I probably hit this. I will verify this tomorrow.

**Comment by isidorn** [comment] 2020-09-03 14:50
Works fine now, thanks!
