### ISSUE TITLE
Cache resolved location of browser to avoid launchservices timeout on OSX

### ISSUE THREAD

**Issue by markmcdowell** [microsoft/vscode-js-debug#570] opened 2020-07-10 14:59 UTC
**Describe the bug**
Debugging via chrome appears to broken after upgrade.

**To Reproduce**
1. Goto debug section
2. Click settings and add basic Launch Chrome
3. Click run
4. See error:

```
Error processing launch: Error: Could not attach to main target
	at Object.t.timeoutPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33028)
	at f.prepareLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2619737)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async f.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2620329)
	at async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25637)
	at async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25208)
	at async Promise.all (index 6)
	at async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:24468)
	at async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2459238)
```
**Log File**

Gz json file seems to be corrupt.

**VS Code Version:** 1.47.0

**Additional context**
MacOSX

**Comment by connor4312** [comment] 2020-07-10 15:09
@markmcdowell this indicates that the debugger could not find a page matching the "urlFilter" given in your launch config within 10 seconds.

Could you share your launch config?

**Comment by markmcdowell** [comment] 2020-07-10 15:14
The launch config was the default generated.

Tried with:

```
{
  "name": "Launch Chrome",
   "request": "launch",
   "type": "pwa-chrome",
   "url": "http://localhost:8080",
   "webRoot": "${workspaceFolder}"
}
```

and 
```
{
   "type": "chrome",
   "request": "launch",
   "name": "Launch Chrome",
   "sourceMaps": true,
   "url": "http://localhost:8000",
   "webRoot": "${workspaceFolder}"
}
```

I think the issue is actually https://github.com/microsoft/vscode-chrome-debug/issues/1023 I've downgraded the Debugger for Chrome and all working again.

**Comment by connor4312** [comment] 2020-07-10 15:17
Can you enable `trace: true` and share the resulting log file?

**Comment by markmcdowell** [comment] 2020-07-10 15:21
Sure:

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4903946/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment] 2020-07-10 15:31
Thanks! Looks like a different problem than the issue you linked. Someone reported it a few days ago, also on OSX, but I wasn't able to root cause it yet.

Could you please try installing this build of the extension https://memes.peet.io/img/js-debug-for-issue-570.vsix (downloading it and then running "Install from VSIX" on the command palette/cmd+shift+p) and capturing trace logs again? That will help me narrow down where it's getting hung up.

**Comment by markmcdowell** [comment] 2020-07-10 15:36
Here you go:

[vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode-js-debug/files/4904012/vscode-debugadapter-2.json.gz)

**Comment by connor4312** [comment] 2020-07-10 16:01
Can you try that again and check this box temporarily? 

![](https://memes.peet.io/img/20-07-ebb3afdb-3433-4d73-833c-95f77058a7ea.png)

I built this off master which is version 1.47.2 while stable is a hotfix ahead at version 1.47.3 -- from the logs it looks like it auto-updated right after you installed it 😛

**Comment by markmcdowell** [comment] 2020-07-10 16:05
Ah ok, I've reinstalled and made sure it's still on 1.47.2 and generated these logs:

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4904171/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment] 2020-07-10 16:25
Okay, thanks!

It looks like the thing eating up time for you is trying to find the path to Chrome on your machine. To do this we read output from OSX' launch services tool. You should be able to get around this by either:

- Increasing the `timeout` property of your launch.json, e.g. to 20 seconds from 10 seconds `timeout: 20000`
- Manually specifying the path to Chrome in the `runtimeExecutable` which will avoid having to run discovery logic.

This seems to have a pretty low incidence rate; I think a decent solution here is caching the browser path to avoid needing to look up multiple times. It will still time out once in this case, but should thereafter work.

**Comment by markmcdowell** [comment] 2020-07-10 16:30
Yeah specifying 20 seconds makes it work, just to note with v4.12.8 of the debugger for chrome it starts straight away without any delay.

**Comment by connor4312** [comment] 2020-07-10 16:38
Yea, the previous debugger just [probed pre-set paths](https://github.com/microsoft/vscode-chrome-debug/blob/master/src/utils.ts#L9-L34). The downside is that if you have the browser installed on some non-default path, you would of course need to fiddle with configuration. But we could also do the probing to provide fast launches for common cases

**Comment by connor4312** [comment] 2020-07-10 19:54
This will be fixed in [today's nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (published at 5 PM PST). Thank you for your help in diagnosing this!

**Closed** 2020-07-10 19:53 UTC
Labels: bug

**Comment by stanimiryakimov** [comment] 2020-07-31 08:46
@connor4312 Hey there. I've bumped into the same issue 
`Error processing launch: Error: Could not attach to main target
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33351` when I try to open in debug mode. I've tried to extend the `timeout: 20000` but the above error still persists.

**Comment by connor4312** [comment] 2020-07-31 14:56
@stanimiryakimov thanks for the report, are you able to collect a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by vikramvi** [comment] 2020-08-04 11:25
getting below error

Mac 10.13.6 +  VS Code 1.47.3 + Debugger for chrome 4.12.9

**launch.json**

`"version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "file": "${workspaceFolder}"
    }
  ]`


**Error dialog**

`Error processing launch: Error: Could not attach to main target
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33351
	at async _.prepareLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2620406)
	at async _.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2621006)
	at async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25725)
	at async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25296)
	at async Promise.all (index 6)
	at async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:24556)
	at async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2459787)`

**Comment by vikramvi** [comment] 2020-08-04 11:28
@connor4312 please re-open ticket as issue still exists

**Comment by connor4312** [comment] 2020-08-04 15:17
@vikramvi please see https://github.com/microsoft/vscode/issues/102529#issuecomment-658453060

**Comment by spacedog4** [comment] 2020-08-05 12:30
I soulved by removing `http://` from url
