### ISSUE TITLE
Improve breakpoint predictor caching for large projects

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1149] opened 2021-12-04 21:02 UTC
I sometimes see breakpoints being very slow to be set when debugging vscode. Here's a log where it took several seconds for the breakpoint to become solid red. This is using the normal "VS Code" launch config and code-oss was not very busy at the moment I set the breakpoint in searchView.ts.

[vscode-debugadapter-bd6f7e46.json.gz](https://github.com/microsoft/vscode-js-debug/files/7654685/vscode-debugadapter-bd6f7e46.json.gz)

**Comment by seanfoltz** [comment] 2021-12-05 09:16
Ok

**Comment by connor4312** [comment] 2021-12-17 21:39
It looks like that is just time in the breakpoint predictor. Just doing some quick local tests, essentially all the time is spent doing the file search.

I think there is possibly some smarter caching that can be done if we avoid ripgrep, for example by knowing file mtimes, remembering the last sourcemap we saw if the mtime matches (which we do today, but only after discovering the sourcemap string), and not bothering reading the file if it doesn't match.

**Comment by joaomoreno** [comment] 2022-07-07 08:46
Is this maybe a dupe of https://github.com/microsoft/vscode/issues/153470?

**Closed** 2022-12-30 09:09 UTC
Labels: bug
