### ISSUE TITLE
Getting "cannot edit in read-only editor" when trying to edit a file from a dependency project while debugging 

### ISSUE THREAD

**Issue by marchant** [microsoft/vscode-js-debug#669] opened 2020-07-29 19:13 UTC
I use symlinks in node_modules in node.js to be able to work efficiently on projects that are used together. Until the new debugger became the default, when hitting a breakpoint and realizing I needed to change some code, I could directly edit the file in front of me when I had a breakpoint triggered, make changes, then restart to test. Now that file is in a read-only editor and it's killing my productivity. 

What's the way to revert to the previous behavior I rely on, without reverting to the previous debugger? And if not possible, is there a way to revert to the previous debugger in the mean time?

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Thanks!

**Comment by connor4312** [comment] 2020-07-30 20:01
Thanks for the issue. I'm having some trouble reproducing this with an `npm link`'d module locally on OSX. Are you able to collect a trace log using the instructions in the issue template?

**Comment by marchant** [comment] 2020-08-01 00:15
Hi @connor4312 I added the trace and got a json log, but there are quite a bunch of info about the project I'm working on that I don't necessarily want to make public at this time, any chance you could guide me to look for what you'd need in there?

**Comment by connor4312** [comment] 2020-08-03 05:46
Sure, the first thing I want to look at is the first frame of the "stackTrace" request -- enter "stackTrace" in the grep box on `https://microsoft.github.io/vscode-pwa-analyzer/index.html`, filter for `dap.send`, and grab the first response.

Because it's a read-only editor, the `sourceReference` there should be != 0. The first thing to check is whether the `path` in that source is correct.

**Comment by connor4312** [comment] 2020-08-13 17:03
Closing for lack of repro/info. If you still run into this and are able to collect that info, let me know!

**Closed by connor4312** 2020-08-13 17:03 UTC
Labels: bug, needs more info

**Comment by marchant** [comment] 2020-10-08 23:57
@connor4312 sorry for not following up, "enableContentValidation": false worked great. But it stopped working with: vscode 1.49.3 and JavaScript Debugger (Nightly) v2020.9.281. By the way, I'm just using unix symlinks, not npm link.

Now when it start I get:
Property enableContentValidation is not allowed.

What can I do to get back that important productivity?! Thanks!

**Comment by Mactarvish** [comment] 2022-09-04 15:37
> 

setting "enableContentValidation": false in launch.json exactly works, thanks!

**Comment by Mactarvish** [comment] 2022-09-04 15:37
> 

setting "enableContentValidation": false in your launch.json  exactly works! Thanks

**Comment by Waffle1434** [comment] 2023-03-15 19:38
Not allowed
![image](https://user-images.githubusercontent.com/8021358/225424025-8266d9cc-bb4b-4916-a260-cb1945f79157.png)

**Comment by connor4312** [comment] 2023-03-15 19:50
This is the JavaScript debugger. You're trying to debug Python.
