### ISSUE TITLE
Step Into with ignored code has spurious steps on node 12

### ISSUE THREAD

**Issue by gordonmleigh** [microsoft/vscode-js-debug#889] opened 2020-12-11 09:49 UTC
**Describe the bug**
Step Into on `console.log` with `node_internals` ignored stops results in multiple steps. Stepping also doesn't follow the async execution flow.

**To Reproduce**
See [repro repository](https://github.com/gordonmleigh/debug-bork) case 2.

**Log File**
See [repro repository](https://github.com/gordonmleigh/debug-bork) `case2*.log.json`

**VS Code Version:**

Version: 1.52.0-insider
Commit: dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66
Date: 2020-12-10T16:23:20.433Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**also tried on:**

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Additional context**

See the linked repository for debugger launch settings and repro code.

**Comment by connor4312** [comment] 2020-12-15 18:17
This looks like a bug -- or, a behavior -- in v8. We use 'blackbox patterns' to skip files, it seems like V8 gives up after a point and pauses anyway. This behavior is different on 14 (#888), so closing.

**Comment by connor4312** [comment] 2020-12-15 18:18
Actually, 15 behaves the same way. So I'll re-open this and open an issue on Node.

**Comment by gordonmleigh** [comment] 2020-12-17 15:17
Isn't #888 basically the opposite behaviour to this? I.e. this is stopping too much, and #888 isn't stopping at all after a point. I've not spent a lot of time trying to look into the implementation specifics, only my own repro cases. To be clear, the three bugs I filed together were my attempt at minimal working examples for debugger problems I see all the time in real projects that together make it _incredibly_ frustrating to actually debug anything.

I mention in this one that the debug stepping doesn't stay with the logical execution on an await, but instead jumps to something else. On thinking about it though, I guess because of the evented nature of node, there's nothing anyone can do about that? It means that the only way to debug async code is to remember to set a breakpoint on the statement following every await.

**Comment by connor4312** [comment] 2020-12-17 15:47
#888 is the opposite, but that seems exclusive to Node 14, and Node 15 is back to the behavior in this issue. I suspect the issue is something to deal with async code, since looking at the log file we always end up paused in the "async inspector" code. We'll see what the Node team has to say.

**Comment by connor4312** [comment] 2021-02-04 19:44
Closing pending upstream update.

**Closed by connor4312** 2021-02-04 19:44 UTC
Labels: bug, upstream
