### ISSUE TITLE
Disabling breakpoints while debugging doesn't work, debugger keeps stopping on it until program is restarted

### ISSUE THREAD

**Issue by marchant** [microsoft/vscode-js-debug#679] opened 2020-08-01 18:53 UTC
This is debugging node.js code if that matters.

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by connor4312** [comment] 2020-08-01 20:31
Please try the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) -- I fixed something like this earlier this month.

If it doesn't work, please collect a trace log using the instructions in the issue template!

**Comment by marchant** [comment] 2020-08-01 22:52
Thanks, fixed indeed!

**Comment by marchant** [comment] 2020-08-25 22:21
With @id:ms-vscode.js-debug-nightly, I'm seeing this issue again. Wether I disable control-click from the dot by the code, or the check box in the breakpoint list, and even if I remove the breakpoint entirely, it stays alive. It's really painful :-( ! Thanks for taking a look!

**Comment by connor4312** [comment] 2020-08-25 22:46
Can you capture a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by marchant** [comment] 2020-08-25 23:04
Will try, I assume you'd like me to reproduce the issue while trace is on ?

**Comment by connor4312** [comment] 2020-08-25 23:17
Yep!

**Comment by marchant** [comment] 2020-08-25 23:38
ok, will do, I'm also still struggling with the fact that the file being debugged is read-only, and there's no easy open of an editable one. I'm not sure if that change was intentional, but obviously when I was able to edit directly, which I very much would like back, I'd restart the program after my changes.

**Comment by connor4312** [comment] 2020-08-25 23:54
The trace file will help diagnose what's wrong there.

**Comment by marchant** [comment] 2020-08-25 23:55
👍🏻

**Comment by marchant** [comment] 2020-08-26 16:16
Sent to your email last night

**Comment by connor4312** [comment] 2020-08-26 16:31
How are scripts being loaded? Do you have anything like Babel or other things hooking into your require's? Most of your problems are due to the files on disk not matching those that are actually running in V8 (and the running files don't have sourcemaps, so we treat them as separate files from those that exist on disk.)

**Comment by connor4312** [comment] 2020-08-26 16:58
I think the breakpoint getting stuck is an internal race caused by an issue in VS Code. The debug protocol has a `setBreakpoints` request, which contains a file and a complete set of all the breakpoints which should be in that file. What I'm seeing is that we get a bunch of `setBreakpoints` requests for the same ('ephemeral') file, each with a different breakpoint.

![](https://memes.peet.io/img/20-08-ed5a0242-341e-4cf5-a35e-d84d26a5114c.png)

The correct behavior would be for us to un-set every breakpoint except for the last one... which we do internally, but it looks like one of the breakpoints set on the Node side of things isn't unset.

All of the above issues should be fixed for you once the file matching issue is resolved. You can also disable content checking by setting `enableContentValidation: false` in your launch.json, but I am interested in determining the root cause to make sure it's not js-debug that's misbehaving.

**Comment by marchant** [comment] 2020-08-27 05:07
I use our own isomorphic require, which works in both browser and node eval() the code ourselves, which includes a //@ sourceURL=" + module.location at the end of what we compile. All was working perfectly fine before the new debugger was introduced ;-) So that file matching is a problem introduced since with the new debugger. I have no issue debugging in chrome for example. It doesn't feel right that I'd have to change something when all worked fine, right ?!

**Comment by connor4312** [comment] 2020-08-27 05:13
The file matching is a new bit of functionality introduced with the debugger. The matching ability allows us to debug tools like ts-node or @babel/register that transpile files in-place. In these cases, we get multiple sources for a single apparent file and need to determine what to mark as ephemeral. js-debug following the same logic in your case -- just your compiled files don't have sourcemaps like babel or ts-node would add, so it can only place the breakpoints in the ephemeral versions of the file.

It sounds like you can do one of two things here:
1. Use the option `enableContentValidation: false` as I mentioned above
1. Have your loader generate a source map for the file, which we will trust to be correct

**Comment by marchant** [comment] 2020-08-27 05:53
Would there be a different outcome pro/con between  1 and 2? Source maps as described heure: https://github.com/mozilla/source-map ?

**Comment by connor4312** [comment] 2020-08-27 15:24
(2) is more complex and involves work on your end to create the sorucemaps. But it's the more correct solution if you're modifying the source of files as you load them.  (1) is the easy solution if not.

**Closed** 2020-08-27 18:03 UTC
Labels: *as-designed
