### ISSUE TITLE
pwa-chrome launch and attach doesn't hit break points

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-js-debug#271] opened 2020-01-28 11:14 UTC
Testing https://github.com/microsoft/vscode/issues/89393  on Windows

- Add the pwa- prefix to the Launch VS Code debug configuration in the vscode project.
- Set a breakpoint (You can do this before or after running the configuration)
- Run that launch config
Expected: The break point resolves and is hit when the code path is run.
Actual: I can't get any breakpoints to resolve so none are hit.

I tried commenting out the "Settings for js-debug" that are in that launch config, and it made no difference.

**Comment by chrmarti** [comment] 2020-01-28 14:44
I can debug as usual when launching, but not when attaching to Chrome. (On Mac.)

When attached the breakpoints don't register (neither in TS nor in JS):
![image](https://user-images.githubusercontent.com/9205389/73273957-10006900-41e5-11ea-9c64-41320268cf5b.png)

**Comment by connor4312** [comment] 2020-01-28 22:50
@alexr00 @chrmarti can you enable `trace: true` and share your logs files? Having trouble repo'ing, vs code launch and tour of heroes both work well for me.

**Comment by connor4312** [comment] 2020-01-28 22:54
@alexr00 can you enable trace: true and share your logs files?

@chrmarti in your screenshot, I don't see any sessions in the Call Stack view. This indicates that we couldn't find a target to attach to, most likely because we don't have a page matching the `url` pattern in your launch config. In my tour of heroes config I have `"url": "http://localhost:4200/*",`. Do you have something different in yours / did the config you have work for the existing debugger?

**Comment by chrmarti** [comment] 2020-01-29 08:43
Putting the exact URL there (`"http://localhost:3000/dashboard"`) shows the same behavior. Using something else shows an error dialog:
![image](https://user-images.githubusercontent.com/9205389/73340811-b1d29500-427b-11ea-84ba-be31f0960776.png)

**Comment by alexr00** [comment] 2020-01-29 09:58
[renderer1.log](https://github.com/microsoft/vscode-js-debug/files/4127267/renderer1.log)

[exthost.log](https://github.com/microsoft/vscode-js-debug/files/4127273/exthost.log)

**Comment by connor4312** [comment] 2020-02-04 00:09
Sorry, I should have specified more about what logs I was after!

When you enable trace: true, the debug console on the debugging process will print a file where logs are written. It'll look something like this--that's the file I'm after:

![image](https://user-images.githubusercontent.com/2230985/73701808-98788100-469f-11ea-825a-fc2f62556c53.png)

**Comment by alexr00** [comment] 2020-02-04 08:48
[vscode-debugadapter.txt](https://github.com/microsoft/vscode-js-debug/files/4152203/vscode-debugadapter.txt)

**Comment by connor4312** [comment] 2020-02-05 16:50
@isidorn @weinand Alex and I debugged this over Live Share this morning (debugging over live share is super cool, by the way!) and it seemed like it might be some VS Code related thing.

Here's what happens. Like all sessions in js-debug, there's the top level "wrapper" sessions, and then debugees come in as children. The top level session works fine and it creates a session which is loopbacked to VS Code<sup>[1](https://github.com/microsoft/vscode-js-debug/blob/master/src/ui/sessionManager.ts#L173-L183)</sup>. The `__pendingTargetId` is what we use to reference the target we're holding onto to 'inject' into the new session.

I see this go through the Chrome config resolver, which doesn't do much except for apply defaults, which we actually don't really care about. [This](https://user-images.githubusercontent.com/2230985/73862939-24032680-47f4-11ea-9329-872fb857608a.png) is the config that gets returned. No errors get thrown as far as I can see. And then, nothing happens. The SessionManager (which is the registered debug descriptor factory) doesn't get a request, the session just stops.

As with all the best bugs, I can't reproduce this on my Windows or OSX machines. Any ideas on what might be happening?

**Comment by isidorn** [comment] 2020-02-05 16:55
So the gist is:
Breakpoints do not get sent to child session? Or none of the requests get sent to the child session?

@alexr00 Does it reproduce if you manually click on the child session in the callstack view?

**Comment by weinand** [comment] 2020-02-05 17:15
@connor4312 if I interpret your last comment correctly you are saying that no child session is created? 
If that is correct: are you calling `vscode.debug.startDebugging()` for a child session which this does not result in a call to the `createDebugAdapterDescriptor` method of your debug descriptor factory?

**Comment by connor4312** [comment] 2020-02-05 17:41
@weinand that's correct, the issue is that the child session is never actually created.

**Comment by weinand** [comment] 2020-02-05 18:34
@connor4312 @isidorn so we only need to debug why "startDebugging" fails to call the factory.

**Comment by connor4312** [comment] 2020-02-05 23:20
> If that is correct: are you calling vscode.debug.startDebugging() for a child session which does not result in a call to the createDebugAdapterDescriptor method of your debug descriptor factory?

Yes. I can verify:

 1. [startDebugging](https://github.com/microsoft/vscode-js-debug/blob/master/src/ui/sessionManager.ts#L180) is called
 2. we [return a config](https://github.com/microsoft/vscode-js-debug/blob/master/src/baseConfigurationProvider.ts#L41) (screenshotted above)
 3. [createDebugAdapterDescriptor](https://github.com/microsoft/vscode-js-debug/blob/master/src/ui/sessionManager.ts#L119) on the sessionManager ([registered](https://github.com/microsoft/vscode-js-debug/blob/master/src/extension.ts#L74) for that debug type) is not called

**Comment by alexr00** [comment] 2020-02-06 08:47
@isidorn there's nothing in the callstack to click on.

**Comment by weinand** [comment] 2020-02-06 10:59
@alexr00 yes, there is no debug session at all, so the issue is completely unrelated to breakpoints.

**Comment by connor4312** [comment] 2020-02-21 17:52
I'm seeing this happening very reliably in remote debugging (https://github.com/microsoft/vscode-js-debug/issues/337) iff I start the server before I start the debug session--which allows the page to load instantly (without the server, the remote debugging process launches chrome which then loads until the server starts). Seems like a race condition. Adding a bunch of console.logs (since debugging it changes timing and makes it work 😛 )

![image](https://user-images.githubusercontent.com/2230985/75058305-9ed46e80-548f-11ea-9926-8033b13058f6.png)

1. The top level session's config is resolved. All normal.
2. We get a call to createDebugAdapterDescriptor as expected. Still all good. We create our debug adapter and then call the companion to launch the server on the UI side.
3. We're now attached to the browser and see there's a new page we can attach to! We call vscode.debug.startDebugging with that `__pendingTargetId` that we want to attach to.
4. This loops back through the standard config resolution process.
5. And then nothing happens--the debug adapter descriptor factory doesn't get any calls.

**Comment by isidorn** [comment] 2020-02-25 14:54
@connor4312 we could do a meeting to look into this issue together. If you would like that feel free to book something in my calendar.

**Comment by isidorn** [comment] 2020-03-04 11:11
Should be fixed via https://github.com/microsoft/vscode/issues/91969
If this is not the case let me know and we can reopen the vscode issue and continue the discussion there.

Thanks all for providing details.

**Closed by isidorn** 2020-03-04 11:11 UTC
Labels: under-discussion

**Comment by alexr00** [comment] 2020-03-11 10:01
Confirmed that this is fixed :)

**Comment by isidorn** [comment] 2020-03-11 11:49
@alexr00 thanks a lot!
