### ISSUE TITLE
Line numbers in profiles when using in-place transpilation are not correct

### ISSUE THREAD

**Issue by yolpsoftware** [microsoft/vscode-js-debug#559] opened 2020-07-07 20:02 UTC
I ran the new VS Code Javascript profiler several times, in two different projects in NodeJS. Those projects involve many async operations and anonymous methods, so most methods do not appear with a name in the profiler output. The only thing that would enable me to correctly identify the method would be the line numbers.

However, those line numbers seem to always be wrong. For one file with about 1000 lines of code, most of the line numbers are between 4 and 20, so they are off quite far. On StackOverflow, another user confirmed that on their machine, the line numbers are wrong too (see comments in the linked answer): https://stackoverflow.com/a/61585758/377011

Now, before I submit a reproducible demo: **Should** those line numbers be correct? Or is that still work-in-progress?

If it's a bug you are not yet aware of, I'd be happy to submit a repro.

**VS Code Version:** 1.46.1

**Comment by connor4312** [comment] 2020-07-07 21:23
There's some ongoing polish on the profile visualizer, but line numbers should be correct. If you are able to create a reproduction where it doesn't work, that would be appreciated 🙂

**Comment by connor4312** [comment] 2020-07-08 16:58
Fyi there were cases where time samples were misassigned. This would not have affected the line numbers, but would have reported the time spent in functions incorrectly -- see https://github.com/microsoft/vscode-js-debug/issues/561

**Comment by yolpsoftware** [comment] 2020-07-09 15:15
@connor4312 thanks, here's a repro:

https://github.com/yolpsoftware/vscode-linenumbers

Steps to reproduce the behavior:

- Checkout the git repo above, run yarn or npm.
- Open index.ts in VSCode, press F5 to run it (launch.json runs the currently opened file).
- You'll get some strange error involving module ts-node/register which could not be loaded. Ignore it, press F5 again.
- Now the script should run, and you should land at the debugger statement on line 5.
- Start a profiling session (Call Stack panel, click on "Take Performance Profile" to the right of "index.ts"). Choose a duration of 1 or 10 seconds.

For 1 second, I get the following profile output:

![image](https://user-images.githubusercontent.com/1302357/87057020-a8742e00-c206-11ea-992e-3b4a2b8dccdf.png)

This does not make sense:

- There is no line 56 in index.ts
- The method which should have most of the "Self Time" is not anonymous, it should be "getPromise"
- The profile ran for one second. Why are there 18 seconds in "Total Time"?

The 10 seconds profile does not make sense either:

![image](https://user-images.githubusercontent.com/1302357/87057679-76af9700-c207-11ea-8dd5-1aa2182276e1.png)

- `writeUtf8String`? `getColorDepth`?
- Again line 56 in index.ts

Thanks for looking into it!

**Comment by connor4312** [comment] 2020-07-09 16:58
The issue with times in the table are fixed in https://github.com/microsoft/vscode-js-debug/issues/561

The line numbers you're seeing are a result of using ts-node -- essentially in Node the script that node 'thinks' it's running doesn't match the file on disk. It looks like we don't reconcile that when determining line numbers in the profile.

**Comment by connor4312** [comment] 2020-07-09 19:31
Turns out this is because that location is inside a function that _only_ exists in the compiled code. We actually do try to source-map it back into the original file, but there's no mapping at that location to use.

![](https://memes.peet.io/img/20-07-87be58b7-450b-4c42-a230-2f0e27c65b42.png)

If you change your target to `es6` or newer -- which you can do nowadays unless you're targeting Internet Explorer or Node versions <= 4 -- TS does not need to generate this stuff and line numbers work. [Here's the latest mappings](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping)

This debugger only supports Node 8 and above. Due to the fact that this bug is only present when targeting old JavaScript versions when using in-place transpilation on code compiled to a version older than what the debugger itself supports, and the complexity involved in fixing this, I will close this issue as-designed.

**Closed by connor4312** 2020-07-09 19:31 UTC
Labels: bug

**Comment by yolpsoftware** [comment] 2020-07-10 07:53
Thanks for the `es6` hint. No idea why I had it at `es5`. Line numbers are now correct, thank you.
