### ISSUE TITLE
Reuse integrated terminal

### ISSUE THREAD

**Issue by jakubnavratil** [microsoft/vscode-js-debug#899] opened 2020-12-17 01:13 UTC
**Describe the bug**
Re-executing debug target in integrated terminal should reuse terminal instance. Currently it creates new terminal instance for every launch.

This was asked here https://github.com/microsoft/vscode/issues/10940
And implemented here https://github.com/microsoft/vscode/commit/50e91ea8900901278b2e4c26196ed287181dba84

![image](https://user-images.githubusercontent.com/7920929/102425567-db201f00-400d-11eb-8064-9c66eec62445.png)

If anything, this should at least close used terminal after session ends. So it does not add up in terminal list everytime I stop/start new session.
This also creates new terminal instance everytime I hit Restart button.

![image](https://user-images.githubusercontent.com/7920929/102425725-318d5d80-400e-11eb-8911-d109e00bee0d.png)

**To Reproduce**
```javascript
{
            "type": "pwa-node",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run", "start:dev"],
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "console": "integratedTerminal",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "smartStep": true
}
```

**VS Code Version:** 1.53.0-insiders

I don't know if this is actually bug report or feature request, but based on fact that this was implemented in old debugger I suppose it is a bug.

**Comment by connor4312** [comment] 2020-12-17 01:19
This sounds like a duplicate of https://github.com/microsoft/vscode/issues/112055

**Closed by connor4312** 2020-12-17 01:19 UTC
Labels: bug

**Comment by jakubnavratil** [comment] 2020-12-17 01:20
Oh I'm sorry, I was searching for existing issue but could not find it.

**Comment by connor4312** [comment] 2020-12-17 01:23
No worries, better to have a duplicate issue than an unreported one :)
