### ISSUE TITLE
Debugger should reevaluate breakpoints when new sources with the same absolutePath come in

### ISSUE THREAD

**Issue by evgenyFinkin** [microsoft/vscode-js-debug#600] opened 2020-07-14 07:14 UTC
I have a proxy and some process running and the debugger doesn't stop

**Comment by viceice** [comment] 2020-07-14 09:19
Here too, workaround s to add a `debugger` statement to initial break. After it you can add normal breakpoint, which are hit as usual.

**Comment by viceice** [comment] 2020-07-14 09:22
Reproducable here: https://github.com/renovatebot/renovate

Works here: https://github.com/renovatebot/ruby-semver

The difference is renovate is using `jest-circus` instead of `jest-jasmine` as `testRunner`.

**Comment by connor4312** [comment] 2020-07-14 14:12
@evgenyFinkin please collect a trace log using these instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

@viceice it sounds like you're hitting https://github.com/microsoft/vscode/issues/102152. This was fixed in the latest [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension.

**Comment by Megabyteceer** [comment] 2020-07-17 14:09
Same issue. I noticed that for scripts loaded asynchonically breakpoints does not work until you remove and set breakpoint again. I think resend brekpoints to browser after new script loaded will fix all such a bugs.

**Comment by YuryKuvetski** [comment] 2020-07-17 14:17
Same picture as @Megabyteceer described. Realy slowы down development 😞

**Comment by connor4312** [comment] 2020-07-17 14:44
@Megabyteceer @YuryKuvetski please collect a trace log using the instructions posted above.

**Comment by Megabyteceer** [comment] 2020-07-20 13:40
Logs:
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4947968/vscode-debugadapter-0.json.gz)

What i did. Set breakpoint first time, its stopped fine. Page have reloaded dynamically few js scripts. Break point stop working because it was inside one of reloaded scripts. I remove and set this breakpoint and after that breakpoints works fine again.

**Comment by connor4312** [comment] 2020-07-20 14:35
Okay, thanks. It looks like the issue in this case is because the URL changed between reloads -- the breakpoint was set in `?v=1`, but after reload the script was `?v=2`, and we don't re-evaluate a breakpoint when a new source comes in (only a sourcemap, at the moment). I will look at fixing this, but this is a somewhat esoteric build/reload setup, so it may be a little while before I have an opportunity to fix this.

**Closed** 2020-08-26 18:20 UTC
Labels: bug

**Comment by DJ4ddi** [comment] 2020-12-02 18:47
What's the status on this?

I'm having the same issue, which is that scripts with deferred loading (basically everything since I'm working on an Electron app) always lose their breakpoint bindings. As described above, simply disabling and enabling each breakpoint restores the binding, but this is not satisfactory because it prevents me from debugging initialization logic.

Using the old debugger (by disabling the preview), everything works as expected.

**Comment by connor4312** [comment] 2020-12-02 18:59
This is fixed. If you are still experiencing issues, please open a new issue and include the info from the template. Thanks.

**Comment by Megabyteceer** [comment] 2020-12-02 19:32
For me breakpoints still stop working, when i reload same script with ?v=2 parameter.
