### ISSUE TITLE
Debugger pwa-chrome configuration does not stop on breakpoints

### ISSUE THREAD

**Issue by izkrivera** [microsoft/vscode-js-debug#1225] opened 2022-03-22 17:03 UTC
**Describe the bug**

When running the JS Debugger (nightly v2022.3.717) breakpoints are always off (empty dots). Toggling then on the breakpoints panel turns some of them on (red). However, the breakpoints never pause execution.

Configuration on a Next's / typescript running on the localhost:

```
"configurations": [
        {
            "name": "Chrome localhost",
            "type": "pwa-chrome",
            "request": "launch",
            "url": "http://app.XXXXXXXX.local:3000",
        }
    ]
```

**To Reproduce**
1. Add breakpoints to any .tsx file
2. Click on 'Start Debugging'
3. Navigate to where the breakpoint should fire
4. Confirm it does not fire

**Log File**
[vscode-debugadapter-25a5d31c.json.gz](https://github.com/microsoft/vscode-js-debug/files/8326397/vscode-debugadapter-25a5d31c.json.gz)

**VS Code Version:** 1.65.2

**Additional context**
Next's and Typescript, localhost app.

**Comment by connor4312** [comment] 2022-05-04 18:02
This'll be fixed in the upcoming [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Please give it a shot!

**Comment by trinoorrod** [comment] 2022-05-09 01:48
In latest VSCode build, this is broken again.
Previously was not broken, applied update today and now I cannot set breakpoints.
{
            "name": "DESKTOP: Attach to Chrome",
            "port": 9222,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}",
        }

**Comment by trinoorrod** [comment] 2022-05-09 01:56
Just to add: rolling back to VSCode March 2022 (1.66.2), breakpoints function as normal.

**Comment by connor4312** [comment] 2022-05-09 05:45
Sorry, this PR didn't get merged yet. Will ping for reviews on it tomorrow.

**Comment by trinoorrod** [comment] 2022-05-09 06:03
No worries. FWIW, on MacOS between VSCode 1.66.2 and 1.67 debug broke.
We've rolled back to 1.66.2, so no biggie right now.
Will try the nightly to see if your fix has resolved whatever issue we're having and let you know.

**Comment by connor4312** [comment] 2022-05-09 15:43
You're probably not facing the same issue as the poster.

**Comment by trinoorrod** [comment] 2022-05-09 22:42
It's definitely the same bug, we've also seen it before. It seems to be one of those issue where fixing it for one case breaks it for others.
However, can confirm js-debug-nightly resolves the issue for us.

**Comment by connor4312** [comment] 2022-05-09 22:51
If nightly resolves it you're probably hitting https://github.com/microsoft/vscode/issues/148864, which was in the last nightly

**Closed** 2022-05-10 15:22 UTC
Labels: bug

**Comment by TylerLeonhardt** [comment] 2022-06-03 20:04
@izkrivera Can you try out the latest insider build of VS Code: http://code.visualstudio.com/insiders if the issue is fixed there, can you please respond with `/verified` so we can mark this issue as verified to be fixed?
