### ISSUE TITLE
Node processes no longer killed when stopping debugging

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode-js-debug#864] opened 2020-11-25 11:54 UTC
**Describe the bug**
When stopping debugging a Node application in VSC, the Node processes will keep running.

**To Reproduce**
1. Start a Node debugging process.
2. End the session.

**VS Code Version:**
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Additional context**
Probably broken by https://github.com/microsoft/vscode-js-debug/commit/e14d78fd77399279c517ee211c3d51c857d17617
Related to #630

**Comment by connor4312** [comment] 2020-11-25 17:55
I cannot reproduce this, please collect logs files using the instructions in the issue template.

**Comment by oliversalzburg** [comment] 2020-11-26 16:23
I sent you an email with the log.

**Comment by oliversalzburg** [comment] 2020-11-30 09:21
Personally, I could only see one relevant entry in the log, the last line mentioning that killing the process failed. I didn't see anything helpful with more information.

If you want me to check anything specific or record other information, let me know.

**Comment by connor4312** [comment] 2020-12-01 17:33
Thanks, fixed in https://github.com/microsoft/vscode-js-debug/commit/d08340a8d88d8baa5646eba89700929e68f7169d. Not sure why I didn't see this before.

**Closed by connor4312** 2020-12-01 17:33 UTC
Labels: bug
