### ISSUE TITLE
Hot reload with React no longer updates internal map

### ISSUE THREAD

**Issue by ctgbarcalow** [microsoft/vscode-js-debug#1852] opened 2023-10-17 18:04 UTC
**Describe the bug**
While debugging an app created using Create-React-App, changing the code doesn't update the VS Code maps causing the IDE to stop on the wrong line. If I debug from the browser everything looks and acts as expected. This was working up unable about 4 days ago. I don't know what's changed, except for recent VS Code updates.

**To Reproduce**
1.) Install Node, etc...
2.) npx create-react-app debug-test (wait for install)
3.) "npm run start"
4.) Edit the App.js add some code to write to the console and start the debugger. It behaves as expected.
4.b) Create the launch.json file
5.) Change the source so that console.log(...) is on a different line, add more log directives. After the how-reload, the break points shift and the IDE is no longer in sync with the code. But the browser has the right code, and stops on the correct line.
5.) Stop the debug session, and restart it, the IDE and source will again be in sync.
6.) I tested this on 3 different computers.

![image](https://github.com/microsoft/vscode-js-debug/assets/85701261/457fed51-df26-47fa-bef5-cb9aba86cef5)

Launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "msedge",
      "request": "launch",
      "name": "Launch Edge against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

**Log File**

[vscode-debugadapter-b59bc0d1.json.gz](https://github.com/microsoft/vscode-js-debug/files/12936912/vscode-debugadapter-b59bc0d1.json.gz)

**VS Code Version:** 1.81.1 (system setup)

**Additional context**
I've tried uninstall/reinstall vs-code and cleaned out all vs-code files as suggested here:
https://code.visualstudio.com/docs/setup/uninstall

**Comment by connor4312** [comment] 2023-10-17 18:43
Possible duplicate of https://github.com/microsoft/vscode-js-debug/issues/1803#issuecomment-1766757257, please try the nightly build tonight/tomorrow and let me know if you still have issues 🙂

**Comment by connor4312** [comment] 2023-10-23 21:21
Could you please grab another log file on the nightly extension so I can see more about what's up?

**Comment by connor4312** [comment] 2023-10-25 16:09
That log is still on the non-nightly version (1.81.1). Please double check you followed all the steps to enable the nightly extension: https://github.com/microsoft/vscode-js-debug#nightly-extension

**Closed** 2023-10-25 16:24 UTC
Labels: bug, info-needed
